# Array

# creating array 

In [111]:
import numpy as np
arr1= np. arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
import numpy as np
arr2= np.array([1, 2, 3, 4,5])
arr2

array([1, 2, 3, 4, 5])

# Indexing 

In [113]:
print(arr1[5])
print(arr1[-5])

5
5


# Slicing in array

In [114]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
print(arr1[3:])
print(arr1[-7:])

[3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


In [116]:
print(arr1[:7])
print(arr1[:-3])

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]


In [117]:
print(arr1[3:8])
print(arr1[-7:-2])

[3 4 5 6 7]
[3 4 5 6 7]


In [118]:
print(arr1[3:8:2])
print(arr1[-7:-2:2])

[3 5 7]
[3 5 7]


In [119]:
print(arr1[9:4:-2])
print(arr1[-1:-6:-2])

[9 7 5]
[9 7 5]


# Broadcasting

In [120]:
arr1= np. arange(10)
print("arr1 :",arr1)
arr2=arr1[4:]
print("arr2 :",arr2)

arr1 : [0 1 2 3 4 5 6 7 8 9]
arr2 : [4 5 6 7 8 9]


In [121]:
print("arr1 :",arr1)
arr3=arr1+5
arr4=arr1-2
arr5=arr1*10
arr6=arr1/2
print("arr3 :",arr3)
print("arr4 :",arr4)
print("arr5 :",arr5)
print("arr6 :",arr6)

arr1 : [0 1 2 3 4 5 6 7 8 9]
arr3 : [ 5  6  7  8  9 10 11 12 13 14]
arr4 : [-2 -1  0  1  2  3  4  5  6  7]
arr5 : [ 0 10 20 30 40 50 60 70 80 90]
arr6 : [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [122]:
print("arr2 :",arr2)
arr2[:]=23
print("arr2 :",arr2)

arr2 : [4 5 6 7 8 9]
arr2 : [23 23 23 23 23 23]


# Build in function for creating array

1. Diagonals

In [123]:
ar1=np.diag([1,1,1])
ar1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

2. Zeros

In [124]:
ar2=np.zeros((3,2))
ar2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

3. Ones

In [125]:
ar3=np.ones((3,2))
ar3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Matrix

# Creating matrix

In [126]:
#using numpy.matrix()
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [127]:
#using numpy.array()
mat1=np.array(([2,3,4,5],[3,4,5,6],[5,6,7,8]))
mat1

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [128]:
#using numpy.reshape()
m2 = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]]).reshape(4,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# Indexing of Matrix

In [129]:
print(a[1,1])
print(mat1[2,1])
print(m2[-2,-2])

4
6
11


# Slicing

In [130]:
print(mat1,end="\n\n")
print(mat1[1,1:])

[[2 3 4 5]
 [3 4 5 6]
 [5 6 7 8]]

[4 5 6]


In [131]:
mat1[1:,1:]

array([[4, 5, 6],
       [6, 7, 8]])

In [132]:
m2[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

# Matrix Broadcasting

In [133]:
m4 = np.matrix('1 2 3; 3 4 5; 5 6 7; 7 8 9')
m5 = m4[:3,:2]
m5

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [134]:
print("m4 :\n",m4)
m6=m4+5
m7=m4-2
m8=m4*10
m9=m4/2
print("m6 :\n",m6)
print("m7 :\n",m7)
print("m8 :\n",m8)
print("m9 :\n",m9)

m4 :
 [[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]
m6 :
 [[ 6  7  8]
 [ 8  9 10]
 [10 11 12]
 [12 13 14]]
m7 :
 [[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]
 [ 5  6  7]]
m8 :
 [[10 20 30]
 [30 40 50]
 [50 60 70]
 [70 80 90]]
m9 :
 [[0.5 1.  1.5]
 [1.5 2.  2.5]
 [2.5 3.  3.5]
 [3.5 4.  4.5]]


In [135]:
print("m4 :\n",m4)
m4[:]=23
print("m4 :\n",m4)

m4 :
 [[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]
m4 :
 [[23 23 23]
 [23 23 23]
 [23 23 23]
 [23 23 23]]


# Built in method


1. SQRT

In [136]:
import math
math.sqrt(0)

0.0

In [137]:
math.sqrt(9)

3.0

In [138]:
math.sqrt(25.4)

5.039841267341661

2. LOG

In [139]:
import math
math.log(10)

2.302585092994046

In [140]:
math.log(10,8)

1.1073093649624544

In [141]:
math.log2(10)

3.321928094887362

In [142]:
math.log10(10)

1.0

3. EXP

In [143]:
#e= 2.71828, fun is like e^x eg. e^2 written as
math.exp(2)

7.38905609893065

In [144]:
2.71828*2.71828

7.3890461584

In [145]:
math.exp(-3)

0.049787068367863944

In [146]:
math.exp(2.3)

9.974182454814718

# Linear Algebra Operations

1. Addition

In [147]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6] ])
b = np.array([ [7, 8, 9], [1, 2, 3] ])
c = a + b
c

array([[ 8, 10, 12],
       [ 5,  7,  9]])

2. Subtraction

In [152]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6] ])
b = np.array([ [7, 8, 9], [10, 12, 13] ])
c = b - a
c

array([[6, 6, 6],
       [6, 7, 7]])

3. Multiplication

In [153]:
import numpy as np
a = np.array([ [1, 2], [3, 4], [5, 6] ])
b = np.array([ [7, 8, 9], [10, 12, 13] ])
c = np.dot(a, b)
d = np.dot(b,a)
print("c:",c,end=("\n\n"))
print("d:",d)
print("c shape is :", c.shape)
print("d shape is :", d.shape)


c: [[ 27  32  35]
 [ 61  72  79]
 [ 95 112 123]]

d: [[ 76 100]
 [111 146]]
c shape is : (3, 3)
d shape is : (2, 2)


4. Transpose

In [154]:
import numpy as np
a = np.array([ [1, 2], [3, 4], [5, 6] ])
print("Using T operator",a.T,end="\n\n")
print("Using lib method",np.transpose(a))
print("Shape of a is:",a.shape)
print("Shape of its transpose is:",a.T.shape)

Using T operator [[1 3 5]
 [2 4 6]]

Using lib method [[1 3 5]
 [2 4 6]]
Shape of a is: (3, 2)
Shape of its transpose is: (2, 3)


5. Inverse

In [155]:
#can be applied only on square matrix
import numpy as np
a = np.array([ [1, 2,7], [3, 4,8], [5, 6,9] ])
ainverse= np.linalg.inv(a)
print("a is:\n",a)
print("a inverse is:\n",ainverse)

a is:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]
a inverse is:
 [[-1.31172805e+15  2.62345609e+15 -1.31172805e+15]
 [ 1.42103872e+15 -2.84207743e+15  1.42103872e+15]
 [-2.18621341e+14  4.37242682e+14 -2.18621341e+14]]


# Array arithmetic calculations

In [159]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 25, 4, 15, 4])

addarr = np.add(arr1, arr2)
subarr = np.subtract(arr1, arr2)
multarr = np.multiply(arr1, arr2)
modarr = np.mod(arr1, arr2)
remainderarr = np.remainder(arr1, arr2)
divarr = np.divide(arr1, arr2)

print("array 1 :", arr1)
print("array 2 :", arr2)
print("**The Array Items After Perfroming Arithmetic Operations ***")
print("Array Addition = ", addarr)
print("Array Subtraction = ", subarr)
print("Array Multiplication =  ", multarr)
print("Array Modulus = ", modarr)
print("Array Remainder = ", remainderarr)
print("Array division = ", divarr)

array 1 : [10 20 30 40 50]
array 2 : [ 5 25  4 15  4]
**The Array Items After Perfroming Arithmetic Operations ***
Array Addition =  [15 45 34 55 54]
Array Subtraction =  [ 5 -5 26 25 46]
Array Multiplication =   [ 50 500 120 600 200]
Array Modulus =  [ 0 20  2 10  2]
Array Remainder =  [ 0 20  2 10  2]
Array division =  [ 2.          0.8         7.5         2.66666667 12.5       ]
